spring:
  application:
    name: yoremo
  profiles:
    include: secrets
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    pool:
      enabled: true
  jpa:
    open-in-view: false

adapter:
  http:
    the-cat-api:
      base-url: https://api.thecatapi.com
      response-time-out-ms: 3000

logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG
